noted-eip/protorepo

.gitignore, accounts/accounts.proto, accounts/groups.proto, buf.gen.yaml, buf.yaml, noted/accounts/v1/accounts.proto, noted/accounts/v1/groups.proto, noted/notes/v1/notes.proto, noted/recommendations/v1/recommendations.proto, notes/notes.proto, recommendations/recommendations.proto
This PR enforces the [uber v2 protobuf style guide](https://github.com/uber/prototool/blob/dev/style/README.md).
Closes #10.
=> Apply uber v2 protobuf guidelines

noted/notes/v1/notes.proto
Add new block types. Contains breaking changes.
- [ENHANCEMENT] Add list points, image, code, math block types.
- [ENHANCEMENT] Rework `notes.v1.NotesAPI.Block` data structure.
=> Add new block types

noted/recommendations/v1/recommendations.proto
Adds summarization route, request and request in protorepo.
- [ENHANCEMENT] Summarize route in `recommendations.proto`
=> Add summarization

noted/accounts/v1/accounts.proto
Message for account listing
List Account request with pagination only for now
List Account response with accounts matching the request
=> List Account

noted/accounts/v1/groups.proto
add created_at: Timestamp to member and group struct
Fixes related to account-service, members implementation
View detailed information for each team member and the group itself such as seniority
=> feat: add timestamp to member and group struct

noted/accounts/v1/groups.proto
List groups witch account_id is a member
=> add rpc ListGroups from account_id, to get groups information

noted/accounts/v1/tchat.proto
Add the protorepo with tchat request and responses
not sure about send/create/delete responses
Need to know more about update functions
Fixes #<issue number> c74c4dd1653633e69a714a9223992fb737623837
-[ADD] tchat proto in Account
=> feat : add tchat proto

noted/accounts/v1/groups.proto
- [ENHANCEMENT] Add `limit` and `offset` to `ListGroup*`.
=> Add pagination to `ListGroup*`

noted/accounts/v1/accounts.proto
Adding the email_regex field to implement an endpoint that will allow the search of an email based on a regex
=> Add: new field for search bar implementation

buf.gen.yaml, noted/accounts/v1/accounts_pb2_grpc.py, noted/language/v1/language_pb2_grpc.py, noted/mailing/v1/mailing_pb2_grpc.py, noted/notes/v1/notes_pb2_grpc.py
Generates Dart code for all messages and enums.
- [ENHANCEMENT] Add JS/TS stub generation.
- [ENHANCEMENT] Add Dart stub generation.
=> Generate JS/TS & Dart Stubs

noted/notes/v1/groups.proto
=> Members and Invites Endpoints Configuration

noted/notes/v1/notes.proto
Add OnAccountDelete in order to call this function from account-service
- [ENHANCEMENT] notes - OnAccountDelete
=> Add OnAccountDelete

noted/notes/v1/groups.proto
Functions in order to list activities by groups added.
New Activity object composed of : 
- id
- group_id
- type (example : "GROUP_JOINED", "GROUP_LEAVED", "NOTE_ADDED", etc)
- event (example : "<user:123> has added <note:3889> in <folder:1092>")
- created_at (date of creation of the event)
One function `ListActivities()` to list activities by `group_id`
One function `GetActivity()` to get a specific activity by `group_id` and the `activity_id`
=> Activities implemenation

noted/mailing/v1/mailing.proto
add title to emails in header
- [BUGFIX]
- [DOCS]
- ...
=> New Title for email

noted/mailing/v1/mailing.proto
…nse accordingly
Update the name of the RPC and the associate request/response
- [BUGFIX]
- [DOCS]
- ...
=> SendEmail Rename to SendEmails

noted/accounts/v1/accounts.proto
=> fix: remove traling slash

noted/accounts/v1/accounts.proto
=> fix: add account_id in UpdateAccountRequest to identify the account

noted/accounts/v1/accounts.proto
- [BUGFIX]
remove forget password logic from client, comparison between mail-token and  account-token should be done in the back
- [DOCS]
- ...
=> feat: validate forget password token

noted/accounts/v1/accounts.proto
ValidateResetPasswordToken responde with auth token to identify the user while updating the password
- [BUGFIX]
- [DOCS]
- ...
=> Authenticate the user after the ResetPasswordToken is validate 

noted/accounts/v1/accounts.proto
Google connexion 
Implementation of the following endpoint :
```rpc AuthenticateGoogle(AuthenticateGoogleRequest) returns (AuthenticateGoogleResponse) ```
=> fix: Google connexion endpoint

noted/notes/v1/recommendations.proto
New model for the new website widget.
Fixes #56 
New fields of the website widget are : 
```proto
string keyword = 1 [(google.api.field_behavior) = REQUIRED];
string type = 2 [(google.api.field_behavior) = REQUIRED];
string url = 3 [(google.api.field_behavior) = REQUIRED];
string summary = 4;
string image_url = 5;
```
But nobody implemented nothing related with the widgets so no breaking changes
=> New website widget

noted/accounts/v1/accounts.proto
Changed `code` as `access token`
=> fix AuthenticateGoogleRequest parameter

noted/accounts/v1/accounts.proto
I have removed fields that will no longer be used on the proto file
- Remove `InviteLink`, `account_id` and ``valid_until``
=> Fix : remove useless argument inside the proto file

noted/accounts/v1/accounts.proto
=> feat: Upload profile picture and get profile picture

noted/accounts/v1/accounts.proto
=> feat: uppload and get profile picture function

noted/accounts/v1/accounts.proto
=> fix: remove body from get request

noted/accounts/v1/accounts.proto
Endpoint `GetMailsFromIDs` créé pour les services.
Fixes #86
=> Endpoint GetMailsFromIDs

noted/notes/v1/notes.proto
Adds the possibility of removing edit permissions on top of granting them.
- [ENHANCEMENT] New name
- [ENHANCEMENT] Possibility to remove edit permissions
=> Better edit permissions (ex: ability to remove them)

docs/account_service_doc.md, docs/account_service_documentation.md, noted/accounts/v1/accounts.proto
=> Account service technical docs

noted/notes/v1/notes.proto
Basic CRUD for block comments. Should we implement the Update aswell ? ( @gabriel654165  )
- [ENHANCEMENT] Block comments
=> Block Comments CRUD

noted/notes/v1/groups.proto
Added account id in ListActivitiesRequest
Fixes #94
=> List activities by accountId

noted/notes/v1/notes.proto
Add lang (string) information on Note and CreateNote
=> Add lang information on Note and CreateNote

noted/accounts/v1/accounts.proto
send validation token for accountId
=> Send Validation token again

noted/accounts/v1/accounts.proto
=> fix: bdody in get

noted/accounts/v1/accounts.proto
=> feat: is account validate need email and password

noted/notes/v1/notes.proto
=> feat: add score and list score

noted/notes/v1/notes.proto
=> fix; list score route

noted/notes/v1/groups.proto, noted/notes/v1/notes.proto
=> feat: protorepo
